export const tuning = [
  {
    id: 1,
    car: {
      name: "Adventure Compact",
      company: "Seoul Caravans",
      star_rate: 4.2,
      cost_krw: "120,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Compact and ready for any adventure.",
      text2: "Ideal for small groups and city travel.",
      //photo: `${img1}`,
    },
  },
  {
    id: 2,
    car: {
      name: "Luxury Voyager",
      company: "Han River Camping",
      star_rate: 4.8,
      cost_krw: "180,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Spacious luxury for long journeys.",
      text2: "High-end features for maximum comfort.",
      //photo: `${img2}`,
    },
  },
  {
    id: 3,
    car: {
      name: "Eco Cruiser",
      company: "Busan Trail",
      star_rate: 4.4,
      cost_krw: "140,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Environmentally friendly design.",
      text2: "Perfect for nature lovers seeking comfort.",
      //photo: `${img3}`,
    },
  },
  {
    id: 4,
    car: {
      name: "Family Adventurer",
      company: "Jeju Caravan Rentals",
      star_rate: 4.5,
      cost_krw: "160,000",
      license_type: "B",
      number_of_people: 6,
      text1: "Roomy enough for families.",
      text2: "Enjoy long trips with built-in family amenities.",
      //photo: `${img4}`,
    },
  },
  {
    id: 5,
    car: {
      name: "Sunset Escape",
      company: "Gyeonggi Nomads",
      star_rate: 4.3,
      cost_krw: "130,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Perfect for sunsets and evening drives.",
      text2: "Stylish interiors for a cozy experience.",
      //photo: `${img5}`,
    },
  },
  {
    id: 6,
    car: {
      name: "Wild Explorer",
      company: "Daegu Ventures",
      star_rate: 4.6,
      cost_krw: "150,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Built for tough terrains and wild explorations.",
      text2: "Equipped for off-road adventures.",
      //photo: `${img6}`,
    },
  },
  {
    id: 7,
    car: {
      name: "Urban Compact",
      company: "Gangnam Camping",
      star_rate: 4.1,
      cost_krw: "110,000",
      license_type: "B",
      number_of_people: 3,
      text1: "Compact for city roads.",
      text2: "Sleek design ideal for urban getaways.",
      //photo: `${img7}`,
    },
  },
  {
    id: 8,
    car: {
      name: "Mountain Trekker",
      company: "Seoul Caravans",
      star_rate: 4.3,
      cost_krw: "145,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Perfect for mountain trips.",
      text2: "Built to withstand rough conditions.",
      //photo: `${img8}`,
    },
  },
  {
    id: 9,
    car: {
      name: "Beach Dreamer",
      company: "Han River Camping",
      star_rate: 4.7,
      cost_krw: "170,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Ideal for beach outings.",
      text2: "Relaxing interiors for a laid-back vibe.",
      //photo: `${img9}`,
    },
  },
  {
    id: 10,
    car: {
      name: "Nomad Spirit",
      company: "Busan Trail",
      star_rate: 4.6,
      cost_krw: "155,000",
      license_type: "C",
      number_of_people: 5,
      text1: "For the free-spirited traveler.",
      text2: "Rugged design for unlimited adventures.",
      //photo: `${img10}`,
    },
  },
  {
    id: 11,
    car: {
      name: "Island Hopper",
      company: "Jeju Caravan Rentals",
      star_rate: 4.4,
      cost_krw: "140,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Compact and efficient for island travel.",
      text2: "Perfect for scenic coastal trips.",
      //photo: `${img11}`,
    },
  },
  {
    id: 12,
    car: {
      name: "Green Path",
      company: "Seaside Caravans",
      star_rate: 4.2,
      cost_krw: "130,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Environmentally conscious travelers' choice.",
      text2: "Eco-friendly materials and energy-saving.",
      //photo: `${img12}`,
    },
  },
  {
    id: 13,
    car: {
      name: "Off-Road King",
      company: "Gangnam Camping",
      star_rate: 4.8,
      cost_krw: "190,000",
      license_type: "D",
      number_of_people: 7,
      text1: "King of off-road adventures.",
      text2: "Equipped with top-tier suspension and tires.",
      //photo: `${img13}`,
    },
  },
  {
    id: 14,
    car: {
      name: "Scenic Cruiser",
      company: "Daegu Ventures",
      star_rate: 4.5,
      cost_krw: "160,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Great for scenic drives.",
      text2: "Panoramic windows for breathtaking views.",
      ////photo: `${img14}`,
    },
  },
  {
    id: 15,
    car: {
      name: "Ocean Breeze",
      company: "Gyeonggi Nomads",
      star_rate: 4.6,
      cost_krw: "170,000",
      license_type: "C",
      number_of_people: 6,
      text1: "Brings the ocean to you.",
      text2: "Perfect for coastal road trips.",
      ////photo: `${img15}`,
    },
  },
  {
    id: 16,
    car: {
      name: "Star Gazing Lounge",
      company: "Seoul Caravans",
      star_rate: 4.9,
      cost_krw: "200,000",
      license_type: "D",
      number_of_people: 7,
      text1: "Ideal for stargazing nights.",
      text2: "Built with panoramic roof for night views.",
      //photo: `${img16}`,
    },
  },
  {
    id: 17,
    car: {
      name: "Wilderness Trek",
      company: "Han River Camping",
      star_rate: 4.4,
      cost_krw: "145,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Takes you deep into nature.",
      text2: "Built tough for wilderness exploration.",
      //photo: `${img17}`,
    },
  },
  {
    id: 18,
    car: {
      name: "Comfort Cruiser",
      company: "Busan Trail",
      star_rate: 4.3,
      cost_krw: "150,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Offers a comfortable ride for all.",
      text2: "All about cozy and relaxed travel.",
      //photo: `${img18}`,
    },
  },
  {
    id: 19,
    car: {
      name: "Eco Trek",
      company: "Jeju Caravan Rentals",
      star_rate: 4.5,
      cost_krw: "165,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Eco-friendly and efficient.",
      text2: "Minimal impact, maximum adventure.",
      //photo: `${img19}`,
    },
  },
  {
    id: 20,
    car: {
      name: "Adventure Seeker",
      company: "Seaside Caravans",
      star_rate: 4.7,
      cost_krw: "180,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Built for thrill-seekers.",
      text2: "Comes with advanced safety features.",
      //photo: `${img20}`,
    },
  },
  {
    id: 21,
    car: {
      name: "Mountain Climber",
      company: "Gyeonggi Nomads",
      star_rate: 4.4,
      cost_krw: "150,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Perfect for mountainous regions.",
      text2: "Enhanced traction for stability on slopes.",
      //photo: `${img21}`,
    },
  },
  {
    id: 22,
    car: {
      name: "Sunrise Dream",
      company: "Gangnam Camping",
      star_rate: 4.8,
      cost_krw: "185,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Wake up to stunning sunrises.",
      text2: "Large windows for incredible views.",
      //photo: `${img22}`,
    },
  },
  {
    id: 23,
    car: {
      name: "Compact Traveler",
      company: "Daegu Ventures",
      star_rate: 4.2,
      cost_krw: "130,000",
      license_type: "B",
      number_of_people: 3,
      text1: "Perfect for solo or duo travelers.",
      text2: "Compact and easy to maneuver.",
      //photo: `${img23}`,
    },
  },
  {
    id: 24,
    car: {
      name: "Elite Comfort",
      company: "Han River Camping",
      star_rate: 4.9,
      cost_krw: "210,000",
      license_type: "D",
      number_of_people: 7,
      text1: "High-end comfort and style.",
      text2: "Ideal for luxury-focused travelers.",
      //photo: `${img24}`,
    },
  },
  {
    id: 25,
    car: {
      name: "Nature Lover",
      company: "Jeju Caravan Rentals",
      star_rate: 4.6,
      cost_krw: "170,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Blends well with nature.",
      text2: "Eco-friendly and spacious.",
      //photo: `${img25}`,
    },
  },
  {
    id: 26,
    car: {
      name: "Road Runner",
      company: "Gyeonggi Nomads",
      star_rate: 4.3,
      cost_krw: "140,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Perfect for long stretches of highway.",
      text2: "Efficient and reliable for any journey.",
      //photo: `${img46}`,
    },
  },
  {
    id: 27,
    car: {
      name: "All Terrain",
      company: "Gangnam Camping",
      star_rate: 4.7,
      cost_krw: "175,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Handles all terrains with ease.",
      text2: "Durable and dependable for rough paths.",
      //photo: `${img47}`,
    },
  },
  {
    id: 28,
    car: {
      name: "Coastal Breeze",
      company: "Daegu Ventures",
      star_rate: 4.4,
      cost_krw: "150,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Breezy and light, ideal for coastlines.",
      text2: "Easy on fuel, heavy on experience.",
      //photo: `${img48}`,
    },
  },
  {
    id: 29,
    car: {
      name: "Forest Trek",
      company: "Han River Camping",
      star_rate: 4.5,
      cost_krw: "160,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Perfect for forest adventures.",
      text2: "Sturdy build for natural landscapes.",
      //photo: `${img49}`,
    },
  },
  {
    id: 30,
    car: {
      name: "Solo Expedition",
      company: "Jeju Caravan Rentals",
      star_rate: 4.2,
      cost_krw: "135,000",
      license_type: "B",
      number_of_people: 1,
      text1: "Ideal for solo travel enthusiasts.",
      text2: "Compact yet packed with features.",
      //photo: `${img50}`,
    },
  },
  {
    id: 31,
    car: {
      name: "Family Retreat",
      company: "Seaside Caravans",
      star_rate: 4.6,
      cost_krw: "180,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Built for family outings.",
      text2: "Spacious and kid-friendly interiors.",
      //photo: `${img51}`,
    },
  },
  {
    id: 32,
    car: {
      name: "Desert King",
      company: "Gyeonggi Nomads",
      star_rate: 4.8,
      cost_krw: "190,000",
      license_type: "D",
      number_of_people: 5,
      text1: "Best for desert terrains.",
      text2: "Advanced cooling and dust protection.",
      //photo: `${img52}`,
    },
  },
  {
    id: 33,
    car: {
      name: "Snow Traveler",
      company: "Gangnam Camping",
      star_rate: 4.5,
      cost_krw: "170,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Perfect for wintery landscapes.",
      text2: "High traction for snowy conditions.",
      //photo: `${img53}`,
    },
  },
  {
    id: 34,
    car: {
      name: "Green Wanderer",
      company: "Daegu Ventures",
      star_rate: 4.4,
      cost_krw: "140,000",
      license_type: "B",
      number_of_people: 3,
      text1: "Eco-friendly caravan for nature lovers.",
      text2: "Sustainable materials and fuel-efficient.",
      //photo: `${img54}`,
    },
  },
  {
    id: 35,
    car: {
      name: "Lakeside Retreat",
      company: "Han River Camping",
      star_rate: 4.7,
      cost_krw: "175,000",
      license_type: "C",
      number_of_people: 4,
      text1: "Ideal for serene lakeside vacations.",
      text2: "Calm and peaceful design.",
      //photo: `${img55}`,
    },
  },
  {
    id: 36,
    car: {
      name: "Rapid Wanderer",
      company: "Jeju Caravan Rentals",
      star_rate: 4.3,
      cost_krw: "150,000",
      license_type: "B",
      number_of_people: 4,
      text1: "Built for quick and easy getaways.",
      text2: "Fast and compact for short trips.",
      //photo: `${img56}`,
    },
  },
  {
    id: 37,
    car: {
      name: "Forest Glider",
      company: "Seaside Caravans",
      star_rate: 4.6,
      cost_krw: "165,000",
      license_type: "C",
      number_of_people: 5,
      text1: "Blends in with forest landscapes.",
      text2: "Smooth drive for quiet roads.",
      //photo: `${img57}`,
    },
  },
  {
    id: 38,
    car: {
      name: "Desert Mirage",
      company: "Gyeonggi Nomads",
      star_rate: 4.5,
      cost_krw: "155,000",
      license_type: "B",
      number_of_people: 3,
      text1: "Built for the desert trails.",
      text2: "Heat-resistant design for arid regions.",
      //photo: `${img58}`,
    },
  },
  {
    id: 39,
    car: {
      name: "River Explorer",
      company: "Gangnam Camping",
      star_rate: 4.7,
      cost_krw: "170,000",
      license_type: "C",
      number_of_people: 4,
      text1: "Made for riverside adventures.",
      text2: "Compact and nimble for riverside paths.",
      //photo: `${img59}`,
    },
  },
  {
    id: 40,
    car: {
      name: "Summit Seeker",
      company: "Daegu Ventures",
      star_rate: 4.9,
      cost_krw: "200,000",
      license_type: "D",
      number_of_people: 6,
      text1: "Perfect for mountainous journeys.",
      text2: "Built to handle steep ascents.",
      //photo: `${img60}`,
    },
  },
];
